from . import test_create
from . import test_configuration_rules
from . import test_product
from . import test_attribute_bounds
from . import test_dimension_values
from . import test_numeric_value_display
from . import test_price_grid
from . import test_session_identity
from . import test_visibility_conditions
from . import test_product_attribute
from . import test_product_config
from . import test_wizard
from . import test_auto_selection
