[project]
name = "odoo-addons-fa-brick-product-configurator"
version = "18.0.20260814.1"
dependencies = [
    "odoo-addon-product_configurator_fa==18.0.*",
    "odoo-addon-product_configurator_fa_mrp==18.0.*",
    "odoo-addon-product_configurator_fa_sale==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
